[env:m5stack-atoms3]
platform   = espressif32
board      = m5stack-atoms3
framework  = arduino

; Velocità seriale per il monitor (debug via USB)
monitor_speed = 115200

; Librerie esterne richieste
lib_deps =
    m5stack/M5Unified @ ^0.2.2
    knolleary/PubSubClient @ ^2.8
    mikalhart/TinyGPSPlus @ ^1.0.3
    tomstewart89/BasicLinearAlgebra @ ^3.6

; Tutte le build_flags devono stare sotto un'unica voce:
build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=0
    -DMQTT_MAX_PACKET_SIZE=512
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1